version: 2
updates:
- package-ecosystem: composer
  directory: /
  schedule:
    interval: monthly
  assignees:
  - tspencer244
  open-pull-requests-limit: 0
  pull-request-branch-name:
    separator: '-'
  reviewers:
  - tspencer244
