---
version: 2
updates:
- directory: "/"
  package-ecosystem: composer
  open-pull-requests-limit: 3
  pull-request-branch-name:
    separator: "-"
  rebase-strategy: disabled
  schedule:
    interval: daily
    time: '15:00'
    timezone: Australia/Perth
  groups:
    composer-minor-patch:
      update-types:
      - minor
      - patch
  reviewers:
  - tspencer244
  assignees:
  - tspencer244
