language: php

php:
  - 7.1
  - 7.2
  - 7.3
  # - nightly

cache:
  directories:
    - $HOME/.composer

before_script:
  - composer install -n

script:
  - composer phpcs
  - composer phpunit

notifications:
  email: false
